packages:
  - "apps/*"
  - "packages/*"

supportedArchitectures:
  os:
    - current
  cpu:
    - current
  libc:
    - current

catalog:
  react: ^19.2.4
  react-dom: ^19.2.4
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  zustand: ^5.0.12
